QuanLySanBanh/Models/BangGiaSan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanBanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGiaSan
    {
        public string MaGia { get; set; }
        public string MaSan { get; set; }
        public Nullable<int> Gio { get; set; }
        public Nullable<decimal> GiaTheoGio { get; set; }
    
        public virtual San San { get; set; }
    }
}

QuanLySanBanh/Areas/Admin/Controllers/BangGiaSansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;
using QuanLySanBanh.Sevices;

namespace QuanLySanBanh.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    [CustomRole(Roles = "Admin")]
    [CustomAuthorize]
    public class BangGiaSansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();
        string LayMaGia()
        {
            var maMax = db.BangGiaSans.ToList().Select(n => n.MaGia).Max();
            int maBG = int.Parse(maMax.Substring(2)) + 1;
            string bg = String.Concat("00000", maBG.ToString());
            return "G" + bg.Substring(maBG.ToString().Length - 1);
        }

        // GET: Admin/BangGiaSans
        public ActionResult Index(string gio = "", string MaSan = "", string gia = "")
        {
            if (MaSan == "")
                MaSan = null;
            if (gio == "")
                gio = null;
            if (gia == "")
                gia = null;
            ViewBag.gio = gio;
            ViewBag.gia = gia;
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan");
            var bangGias = db.BangGiaSans.SqlQuery("BangGiaSan_TimKiem '" + MaSan + "','" + gio + "','" + gia + "'");
            if (bangGias.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            /*var bangGiaSans = db.BangGiaSans.Include(b => b.San);*/
            return View(bangGias.ToList());
        }

        // GET: Admin/BangGiaSans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            return View(bangGiaSan);
        }

        // GET: Admin/BangGiaSans/Create
        public ActionResult Create()
        {
            ViewBag.MaGia = LayMaGia();
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan");
            return View();
        }

        // POST: Admin/BangGiaSans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGia,MaSan,Gio,GiaTheoGio")] BangGiaSan bangGiaSan)
        {
            ViewBag.MaGia = LayMaGia();
            if (ModelState.IsValid)
            {
                bangGiaSan.MaGia = LayMaGia();
                db.BangGiaSans.Add(bangGiaSan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // GET: Admin/BangGiaSans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // POST: Admin/BangGiaSans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGia,MaSan,Gio,GiaTheoGio")] BangGiaSan bangGiaSan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bangGiaSan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // GET: Admin/BangGiaSans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            return View(bangGiaSan);
        }

        // POST: Admin/BangGiaSans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            db.BangGiaSans.Remove(bangGiaSan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySanBanh/Controllers/BangGiaSansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;

namespace QuanLySanBanh.Controllers
{
    public class BangGiaSansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();

        // GET: BangGiaSans
        public ActionResult Index()
        {
            var bangGiaSans = db.BangGiaSans.Include(b => b.San);
            return View(bangGiaSans.ToList());
        }

        // GET: BangGiaSans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            return View(bangGiaSan);
        }

        // GET: BangGiaSans/Create
        public ActionResult Create()
        {
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan");
            return View();
        }

        // POST: BangGiaSans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGia,MaSan,Gio,GiaTheoGio")] BangGiaSan bangGiaSan)
        {
            if (ModelState.IsValid)
            {
                db.BangGiaSans.Add(bangGiaSan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // GET: BangGiaSans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // POST: BangGiaSans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGia,MaSan,Gio,GiaTheoGio")] BangGiaSan bangGiaSan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bangGiaSan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSan = new SelectList(db.Sans, "MaSan", "TenSan", bangGiaSan.MaSan);
            return View(bangGiaSan);
        }

        // GET: BangGiaSans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            if (bangGiaSan == null)
            {
                return HttpNotFound();
            }
            return View(bangGiaSan);
        }

        // POST: BangGiaSans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BangGiaSan bangGiaSan = db.BangGiaSans.Find(id);
            db.BangGiaSans.Remove(bangGiaSan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySanBanh/Controllers/SansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;

namespace QuanLySanBong.Controllers
{
    public class SansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();

        // GET: Sans
        public ActionResult Index()
        {
            String Ngay;
            int Gio;
            Ngay = DateTime.Now.ToString("yyyy-MM-dd");
            Gio = DateTime.Now.Hour;

            DataTable dataTable = new DataTable();
            using (SqlConnection connection = new SqlConnection(db.Database.Connection.ConnectionString))
            {
                using (SqlCommand command = new SqlCommand("select * from fn_DanhSachSanVaTinhTrangTheoNgayTheoGio('" + Ngay + "'," + Gio + ")", connection))
                {
                    connection.Open();

                    using (SqlDataAdapter adapter = new SqlDataAdapter(command))
                    {
                        adapter.Fill(dataTable);
                    }
                }
            }

            if (dataTable.Rows.Count == 0)
            {
                ViewBag.TB = "Không có kết quả";
            }
            List<DataRow> rows = dataTable.AsEnumerable().ToList();
            return View(rows);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySanBanh/Areas/Admin/Views/BangGiaSans/Create.cshtml
@model QuanLySanBanh.Models.BangGiaSan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BangGiaSan</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MaGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaSan, "MaSan", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaSan", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaSan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GiaTheoGio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GiaTheoGio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GiaTheoGio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@
@using (Html.BeginForm("Create", "BangGiaSans", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
<style>
    .group-info {
        margin: 30px 0;
        display: flex;
        justify-content: space-between;
    }

    h5 {
        margin-top: 5px
    }
</style>
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <div style=" background-color: #ee1e46; padding: 16px 88px; color: #fff; width: 500px; text-align:center">
        <h2>Thêm bảng giá sân</h2>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div style="padding: 0 30px; border: 3px solid rgba(255, 255, 255, 0.1); width: 500px;">
        <div class="group-info">
            <h5>Mã giá</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.MaGia, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly", @Value = ViewBag.MaGia } })
                @Html.ValidationMessageFor(model => model.MaGia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Tên sân</h5>
            <div style="width: 211px">
                @Html.DropDownList("MaSan", null, htmlAttributes: new { @class = "form-control" , @style="background-color: #222831" })
                @Html.ValidationMessageFor(model => model.MaSan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Giờ</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.Gio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Giá theo giờ</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.GiaTheoGio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTheoGio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
            @Html.ActionLink("Quay lại danh sách bảng giá sân", "Index", new { }, new { @class = " btn btn-outline-primary" })
            <input type="submit" value="Thêm" class="btn btn-outline-success" />
        </div>
    </div>
</div>
    }

QuanLySanBanh/Areas/Admin/Views/BangGiaSans/Delete.cshtml
@model QuanLySanBanh.Models.BangGiaSan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@*<h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>BangGiaSan</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Gio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GiaTheoGio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GiaTheoGio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.San.TenSan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.San.TenSan)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>*@
<style>
    .group-info {
        margin: 30px 0;
        display: flex;
        justify-content: space-between;
    }
</style>
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <h3 style="color: red">Bạn có muốn xóa bảng giá sân này không?</h3>
    <div style=" background-color: #ee1e46; padding: 16px 88px; color: #fff; width: 500px; text-align: center;">
        <h2>Xóa bảng giá sân</h2>
    </div>
    <div style="padding: 0 30px; border: 3px solid rgba(255, 255, 255, 0.1); width: 500px;">
        <div class="group-info">
            <h5>Mã bảng giá sân</h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.MaGia</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Tên sân:</h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.San.TenSan</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Giờ: </h5>
            <div style="width: 211px">
                <h5 style="word-break:break-word">@Model.Gio</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Giá theo giờ: </h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@string.Format("{0:#,##0} vnđ", @Model.GiaTheoGio)</h5>
            </div>
        </div>
        <div>
            @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color" style="display: flex; justify-content: space-between; margin-bottom: 20px;">
                @Html.ActionLink("Quay lại danh sách bảng giá sân", "Index",new {}, new { @class = "btn btn-outline-primary" })
                <input type="submit" value="Xóa" class="btn btn-outline-danger" />
            </div>
            }
        </div>
    </div>
</div>

QuanLySanBanh/Areas/Admin/Views/BangGiaSans/Edit.cshtml
@model QuanLySanBanh.Models.BangGiaSan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@*<h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BangGiaSan</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaGia)

            <div class="form-group">
                @Html.LabelFor(model => model.MaSan, "MaSan", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaSan", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaSan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GiaTheoGio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GiaTheoGio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GiaTheoGio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@
@using (Html.BeginForm("Edit", "BangGiaSans", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
<style>
    .group-info {
        margin: 30px 0;
        display: flex;
        justify-content: space-between;
    }

    h5 {
        margin-top: 5px
    }
</style>
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <div style=" background-color: #ee1e46; padding: 16px 88px; color: #fff; width: 500px; text-align:center">
        <h2>Chỉnh sửa bảng giá sân</h2>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div style="padding: 0 30px; border: 3px solid rgba(255, 255, 255, 0.1); width: 500px;">
        <div class="group-info">
            <h5>Mã bảng giá sân</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.MaGia, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
                @Html.ValidationMessageFor(model => model.MaGia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Tên sân</h5>
            <div style="width: 211px">
                @Html.DropDownList("MaSan", null, htmlAttributes: new { @class = "form-control" , @style="background-color: #222831" })
                @Html.ValidationMessageFor(model => model.MaSan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Giờ</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.Gio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="group-info">
            <h5>Giá theo giờ</h5>
            <div style="width: 211px">
                @Html.EditorFor(model => model.GiaTheoGio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTheoGio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
            @Html.ActionLink("Quay lại danh sách bảng giá sân", "Index", new { }, new { @class = " btn btn-outline-primary" })
            <input type="submit" value="Lưu" class="btn btn-outline-success" />
        </div>
    </div>
</div>
    }

QuanLySanBanh/Areas/Admin/Views/BangGiaSans/Index.cshtml
@model IEnumerable<QuanLySanBanh.Models.BangGiaSan>

@{
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSan", rowsPerPage: 6);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}
<link href="~/Content/Pagecss/sanListAdmin.css" rel="stylesheet" type="text/css" />
<style>

    p {
        float: left !important;
        display: inline-block;
    }

    #search-form {
        float: left !important;
        display: inline-block;
        font-size: 20px;
        margin-top: 10px;
        font-weight: bold;
        margin-left: 60px;
    }

        #search-form input {
            text-align: center;
            background-color: #222831;
            border: 1px solid white;
            border-radius: 3px;
            color: white;
            margin-left: 20px;
            margin-right: 30px;
        }
    #MaSan {
        display: inline-block;
        background-color: #222831;
        color: white;
        border-radius: 3px;
        border: 1px solid white;
        width: 260px;
        margin-left: 20px;
        margin-right: 30px;
    }
        #gio{
            width: 40px;
        }
        #gia{
            width: 100px;
        }
    #reset {
        font-size: 20px;
        margin-right: 5px;
    }
</style>
<div id="san-list" class="widget-next-match">
    <div class="widget-title">
        <h3>Danh Sách Bảng Giá Sân</h3>
    </div>
    <div class="widget-body mb-3">
        <div class="text-center widget-vs-contents mb-4">

            <p>
                <a href="~/Admin/BangGiaSans/Create" class="btn btn-primary py-3 px-4 mr-3"><i style="margin-right: 10px;" class="fas fa-futbol"></i>Thêm Bảng Giá Sân Mới</a>
            </p>
            @using (Html.BeginForm("Index", "BangGiaSans", FormMethod.Get))

            {
                @Html.AntiForgeryToken()
        <div id="search-form">
            <span>Tên sân</span>
            @Html.DropDownList("MaSan", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
            <span>Giờ </span>
            <input id="gio" type="number" name="gio" value="@ViewBag.gio" />
            <span>Giá theo giờ </span>
            <input id="gia" type="number" name="gia" value="@ViewBag.gia" />
            <a href="~/Admin/BangGiaSans/Index" id="reset"><abbr title="Làm mới"><i class="fas fa-sync-alt"></i></abbr></a>
        </div>
                <input class="btn btn-success py-3 px-2 mr-3" type="submit" name="submit" value="Tìm bảng giá" style="margin-left: 5px;width:110px;
                color:white" />
            }
        </div>

        @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
     grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("MaGia","Mã bảng giá sân"),
    grid.Column("San.TenSan","Tên sân"),//the model fields to display
    grid.Column("Gio","Giờ"),
    grid.Column("GiaTheoGio","Giá Theo Giờ",format:@<text> @item.GiaTheoGio.ToString("#,##0") vnđ  </text>),
/*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
grid.Column("Chức năng", format: @<text>
        <a href="@Url.Action("Edit",
                        new { id = item.MaGia} )" class="btn btn-outline-warning"><abbr title="Cập nhật dữ liệu"><i class="fas fa-edit"></i></abbr></a>
        <a href="@Url.Action("Details",
                        new { id = item.MaGia} )" class="btn btn-outline-info"><abbr title="Xem chi tiết"><i class="fas fa-list-alt"></i></abbr></a>
        <a href="@Url.Action("Delete",
                        new { id = item.MaGia})" class="btn btn-outline-danger"><abbr title="Xóa dữ liệu"><i class="fas fa-trash-alt"></i></abbr></a>
    </text>),

}
)
        <h5 style="text-align: center; color: #ee1e46; font-size: 50px;">@ViewBag.TB</h5>

    </div>
</div>