QuanLySanBanh/Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanBanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DatSans = new HashSet<DatSan>();
        }
    
        public string MaTK { get; set; }
        public string TenTK { get; set; }
        [StringLength(100)]
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> Vip { get; set; }
        public Nullable<int> DiemTich { get; set; }
        public Nullable<bool> Quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatSan> DatSans { get; set; }
    }
}

QuanLySanBanh/Areas/Admin/Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;
using QuanLySanBanh.Sevices;

namespace QuanLySanBanh.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    [CustomRole(Roles = "Admin")]
    [CustomAuthorize]
    public class TaiKhoansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();
        string LayMaTK()
        {
            var maMax = db.TaiKhoans.ToList().Select(n => n.MaTK).Max();
            int maTK = int.Parse(maMax.Substring(2)) + 1;
            string tk = String.Concat("00", maTK.ToString());
            return "TK" + tk.Substring(maTK.ToString().Length - 1);
        }

        // GET: Admin/TaiKhoans
        public ActionResult Index(string maTK = "", string tenTK = "",string sdt="", string vip = "", string quyen = "")
        {
            if (maTK == "")
                maTK = null;
            if (tenTK == "")
                tenTK = null;
            if (sdt == "")
                sdt = null;
            if (vip == "")
                vip = null;
            if (quyen == "")
                quyen = null;
            ViewBag.maTK = maTK;
            ViewBag.tenTK = tenTK;
            ViewBag.sdt = sdt;
            ViewBag.vip = vip;
            ViewBag.quyen = quyen;
            var taiKhoans = db.TaiKhoans.SqlQuery("TaiKhoan_TimKiem '" + maTK + "','" + tenTK + "','" + sdt + "','" + vip + "','" + quyen + "'");
            if (taiKhoans.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(taiKhoans.ToList());
        }

        // GET: Admin/TaiKhoans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Create
        public ActionResult Create()
        {
            ViewBag.MaTK = LayMaTK();
            return View();
        }

        // POST: Admin/TaiKhoans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTK,TenTK,MatKhau,Email,HoTen,SDT,DiaChi,Vip,DiemTich,Quyen")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                taiKhoan.MaTK = LayMaTK();
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/TaiKhoans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTK,TenTK,MatKhau,Email,HoTen,SDT,DiaChi,Vip,DiemTich,Quyen")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/TaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySanBanh/Controllers/SansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;

namespace QuanLySanBong.Controllers
{
    public class SansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();

        // GET: Sans
        public ActionResult Index()
        {
            String Ngay;
            int Gio;
            Ngay = DateTime.Now.ToString("yyyy-MM-dd");
            Gio = DateTime.Now.Hour;

            DataTable dataTable = new DataTable();
            using (SqlConnection connection = new SqlConnection(db.Database.Connection.ConnectionString))
            {
                using (SqlCommand command = new SqlCommand("select * from fn_DanhSachSanVaTinhTrangTheoNgayTheoGio('" + Ngay + "'," + Gio + ")", connection))
                {
                    connection.Open();

                    using (SqlDataAdapter adapter = new SqlDataAdapter(command))
                    {
                        adapter.Fill(dataTable);
                    }
                }
            }

            if (dataTable.Rows.Count == 0)
            {
                ViewBag.TB = "Không có kết quả";
            }
            List<DataRow> rows = dataTable.AsEnumerable().ToList();
            return View(rows);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySanBanh/Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using QuanLySanBanh.Models;

namespace QuanLySanBong_Web.Controllers
{   
    public class TaiKhoansController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();
        string LayMaTK()
        {
            var maMax = db.TaiKhoans.ToList().Select(n => n.MaTK).Max();
            int maTK = int.Parse(maMax.Substring(2)) + 1;
            string tk = String.Concat("00", maTK.ToString());
            return "TK" + tk.Substring(maTK.ToString().Length - 1);
        }

        // GET: TaiKhoans
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
        }
        
        // GET: TaiKhoans/Details/TK005
        [Route("TaiKhoans/Details/{maTK}")]
        public ActionResult Details(string maTK)
        {
            if (maTK == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(maTK);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }


        // GET: TaiKhoans/Edit/5
        [Route("TaiKhoans/Edit/{id}")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTK,TenTK,Email,HoTen,SDT,DiaChi,Vip,DiemTich")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = taiKhoan.MaTK });

            }
            return View(taiKhoan);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void CheckRole(TaiKhoan taikhoan)
        {
            var tk = db.TaiKhoans.Where(a => a.Email.Equals(taikhoan.Email) && a.MatKhau.Equals(taikhoan.MatKhau)).FirstOrDefault();

            if (tk != null)
            {
                // Xác thực thành công

                if (tk.Quyen == true) // Kiểm tra "Quyen" có giá trị "admin" (hoặc 1) hay không
                {
                    // Đặt vai trò "admin" cho người dùng
                    var identity = new ClaimsIdentity(new[] {
                        new Claim(ClaimTypes.Name, tk.TenTK),
                        new Claim(ClaimTypes.Role, "Admin")
                    }, "ApplicationCookie");

                    // Đăng nhập người dùng
                    var ctx = Request.GetOwinContext();
                    var authManager = ctx.Authentication;
                    authManager.SignIn(identity);
                }
            }
        }
    }
}

QuanLySanBanh/Areas/Admin/Views/TaiKhoans/Create.cshtml
@model QuanLySanBanh.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>TaiKhoan</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MaTK, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaTK, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaTK, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenTK, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Vip, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Vip)
                        @Html.ValidationMessageFor(model => model.Vip, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiemTich, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiemTich, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemTich, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quyen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Quyen)
                        @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@
@using (Html.BeginForm("Create", "TaiKhoans", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
<style>
    .group-info {
        margin: 30px 0;
        display: flex;
        justify-content: space-between;
    }

    h5 {
        margin-top: 10px
    }

    .checkbox {
        margin-top: 6px;
        font-size: larger;
        font-weight: 400;
    }
</style>
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <div style=" background-color: #ee1e46; padding: 16px 88px; color: #fff; width: 800px; text-align:center">
        <h2>Thêm tài khoản</h2>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div style="padding: 0 30px; border: 3px solid rgba(255, 255, 255, 0.1); width: 800px;">
        <div class="row" style="display: flex">
            <div class="col">
                <div class="group-info">
                    <h5>Mã tài khoản</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.MaTK, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly", @Value = ViewBag.MaTK } })
                        @Html.ValidationMessageFor(model => model.MaTK, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Tên tài khoản</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Mật khẩu</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", @type = "password"} })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Email</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control"} })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Họ tên</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="group-info">
                    <h5>Số điện thoại</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Địa chỉ</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Thành viên</h5>
                    <div class="checkbox" style="width: 211px">
                        Vip @Html.RadioButtonFor(model => model.Vip, "True", new { @checked = "checked" }) &nbsp;
                        Thường @Html.RadioButtonFor(model => model.Vip, "False")
                        @Html.ValidationMessageFor(model => model.Vip, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Điểm tích</h5>
                    <div style="width: 211px">
                        @Html.EditorFor(model => model.DiemTich, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiemTich, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="group-info">
                    <h5>Loại tài khoản</h5>
                    <div class="checkbox" style="width: 211px">
                        Admin @Html.RadioButtonFor(model => model.Quyen, "True", new { @checked = "checked" }) &nbsp;
                        Khách hàng @Html.RadioButtonFor(model => model.Quyen, "False")
                        @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
            @Html.ActionLink("Quay lại danh sách tài khoản", "Index", new { }, new { @class = " btn btn-outline-primary" })
            <input type="submit" value="Thêm" class="btn btn-outline-success" />
        </div>
    </div>
</div>
    }

QuanLySanBanh/Areas/Admin/Views/TaiKhoans/Index.cshtml
@model IEnumerable<QuanLySanBanh.Models.TaiKhoan>


    @{
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 3);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
    }
    <link href="~/Content/Pagecss/sanListAdmin.css" rel="stylesheet" type="text/css" />
    <style>

        p {
            float: left !important;
            display: inline-block;
        }

        #search-form {
            float: left !important;
            display: inline-block;
            font-size: 20px;
            margin-top: 10px;
            font-weight: bold;
            margin-left: 9px;
        }


            #search-form input {
                text-align: center;
                background-color: #222831;
                border: 1px solid white;
                border-radius: 3px;
                color: white;
                margin-left: 10px;
                margin-right: 20px;
            }

        #MaSan {
            display: inline-block;
            background-color: #222831;
            color: white;
            border-radius: 3px;
            border: 1px solid white;
            width: 260px;
            margin-left: 10px;
            margin-right: 20px;
        }

        #gio {
            width: 140px;
        }

        #maTK {
            width: 100px;
        }

        #reset {
            font-size: 20px;
            margin-right: 5px;
        }

        #radio {
            margin-top: 10px;
            margin-bottom: 10px;
        }

            #radio input {
                width: 15px;
                height: 15px;
                margin-left: 10px;
                margin-right: 10px;
                font-size: 0px;
            }

        #chia {
            margin-left: 100px;
        }
        table{
            font-size: 15px !important;
        }
    </style>
    <div id="san-list" class="widget-next-match">
        <div class="widget-title">
            <h3>Danh Sách Tài Khoản</h3>
        </div>
        <div class="widget-body mb-3">
            <div class="text-center widget-vs-contents mb-4">

                <p>
                    <a href="~/Admin/TaiKhoans/Create" class="btn btn-primary py-3 px-4 mr-3"><i style="margin-right: 10px;" class="fas fa-futbol"></i>Thêm Tài Khoản Mới</a>
                </p>
                @using (Html.BeginForm("Index", "TaiKhoans", FormMethod.Get))

            {
                @Html.AntiForgeryToken()
                <div id="search-form">
                    <div>
                        <span>Mã tài khoản </span>
                        <input id="maTK" type="text" name="maTK" value="@ViewBag.maTK" />
                        <span>Tên tài khoản </span>
                        <input id="gio" type="text" name="tenTK" value="@ViewBag.tenTK" />
                        <span>Số điện thoại </span>
                        <input id="gio" type="number" name="sdt" value="@ViewBag.sdt" />
                    </div>
                    <div id="radio">
                        <span>Thành viên </span>

                        @if (@ViewBag.vip == null)
                        {
                        <input type="radio" name="vip" value="1" /><text>VIP</text>
                        <input type="radio" name="vip" value="0" /><text>Thường</text>
                        }
                        else if (@ViewBag.vip == "1")
                        {
                        <input type="radio" name="vip" checked value="1" /><text>VIP</text>
                        <input type="radio" name="vip" value="0" /><text>Thường</text>
                        }
                        else
                        {
                        <input type="radio" name="vip" value="1" /><text>VIP</text>
                        <input type="radio" name="vip" checked value="0" /><text>Thường</text>
                        }

                        <span id="chia">Loại tài khoản </span>
                        @if (@ViewBag.quyen == null)
                        {
                        <input type="radio" name="quyen" value="1" /><text>Admin</text>
                        <input type="radio" name="quyen" value="0" /><text>Khách hàng</text>
                        }
                        else if (@ViewBag.quyen == "1")
                        {
                        <input type="radio" name="quyen" checked value="1" /><text>Admin</text>
                        <input type="radio" name="quyen" value="0" /><text>Khách hàng</text>
                        }
                        else
                        {
                        <input type="radio" name="quyen" value="1" /><text>Admin</text>
                        <input type="radio" name="quyen" checked value="0" /><text>Khách hàng</text>
                        }
                    </div>
                </div>
                <a href="~/Admin/TaiKhoans/Index" id="reset"><abbr title="Làm mới"><i class="fas fa-sync-alt"></i></abbr></a>
                <input class="btn btn-success py-3 px-2 " type="submit" name="submit" value="Tìm tài khoản" style="margin-left: 5px;width:120px;
                        color:white" />
            }
            </div>

            @grid.GetHtml(
                         tableStyle: "table table-bordered table-hover",
                         footerStyle: "grid-footer",
                         fillEmptyRows: true,
                         mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",
                         columns: new[]  // colums in grid
                         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("DiaChi","Địa chỉ"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Thành viên",format: (@item) => @item.Vip==true?"VIP":"Thường"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Loại tài khoản",format: (@item) => @item.Quyen==true?"Admin":"Khách hàng"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: @<text>
                <a href="@Url.Action("Edit",
                        new { id = item.MaTK} )" class="btn btn-outline-warning"><abbr title="Cập nhật dữ liệu"><i class="fas fa-edit"></i></abbr></a>
                <a href="@Url.Action("Details",
                        new { id = item.MaTK} )" class="btn btn-outline-info"><abbr title="Xem chi tiết"><i class="fas fa-list-alt"></i></abbr></a>
                <a href="@Url.Action("Delete",
                        new { id = item.MaTK})" class="btn btn-outline-danger"><abbr title="Xóa dữ liệu"><i class="fas fa-trash-alt"></i></abbr></a>
            </text>),

   }
   )
            <h5 style="text-align: center; color: #ee1e46; font-size: 50px;">@ViewBag.TB</h5>
        </div>
    </div>