QuanLySanBanh/Controllers/TaiKhoansUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Security.Principal;
using System.Web.Mvc;
using System.Web.Security;
using QuanLySanBanh.Models;
using QuanLySanBanh.Sevices;

namespace QuanLySanBanh.Controllers
{
    public class TaiKhoansUserController : Controller
    {
        private QuanLySanBongEntities db = new QuanLySanBongEntities();


        string LayMaTK()
        {
            var maMax = db.TaiKhoans.ToList().Select(n => n.MaTK).Max();
            int maTK = int.Parse(maMax.Substring(2)) + 1;
            string tk = String.Concat("00", maTK.ToString());
            return "TK" + tk.Substring(maTK.ToString().Length - 1);
        }

        [HttpPost]
        public ActionResult Logout()
        {
            // Xóa cookie xác thực
            FormsAuthentication.SignOut();

            // Xóa các cookie khác nếu cần
            CookieSevices.DeleteCookie(HttpContext.ApplicationInstance.Context, "MaTK");
            CookieSevices.DeleteCookie(HttpContext.ApplicationInstance.Context, "Quyen");

            // Chuyển hướng đến trang đăng nhập
            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult Login(string Email, string MatKhau)
        {
            if (ModelState.IsValid)
            {
                var tk = db.TaiKhoans.FirstOrDefault(a => a.Email == Email);
                if (tk != null)
                {
                    // Kiểm tra mật khẩu
                    bool isPasswordValid = BCrypt.Net.BCrypt.Verify(MatKhau, tk.MatKhau);
                    if (isPasswordValid)
                    {
                        // Đăng nhập thành công, đặt đánh dấu đã xác thực
                        CookieSevices.SetCookie(
                            HttpContext.ApplicationInstance.Context,
                            "MaTK", tk.MaTK.ToString()
                        );

                        // Kiểm tra vai trò và chuyển hướng đến trang tương ứng
                        if (CheckRole(tk))
                        {
                            CookieSevices.SetCookie(
                                HttpContext.ApplicationInstance.Context,"Quyen", "Admin"
                            );
                            return RedirectToAction("Home", "Sans", new { area = "Admin" });
                        }
                        else
                        {
                            return RedirectToAction("Index", "Sans");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Sai tài khoản hoặc mật khẩu");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Sai tài khoản hoặc mật khẩu");
                    return View();
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Register([Bind(Include = "MaTK,TenTK,MatKhau,Email,HoTen,SDT,DiaChi,Vip,DiemTich,Quyen")] TaiKhoan taiKhoan)
        {
            /*// Kiểm tra xem tên đăng nhập đã tồn tại chưa
            if (db.TaiKhoans.Any(tk => tk.TenTK == taiKhoan.TenTK))
            {
                ModelState.AddModelError("", "Tên đăng nhập đã tồn tại.");
                return View(taiKhoan);
            }
            // Kiểm tra xem email đã tồn tại chưa
            else if (db.TaiKhoans.Any(tk => tk.Email == taiKhoan.Email))
            {
                ModelState.AddModelError("", "Email đã tồn tại.");
                return View(taiKhoan);
            }
            else
            {
                
            }*/
            if (ModelState.IsValid)
            {

                try
                {
                    // Mã hóa mật khẩu trước khi lưu vào CSDL
                    string hashedPassword = BCrypt.Net.BCrypt.HashPassword(taiKhoan.MatKhau);
                    // Gán mật khẩu đã được mã hóa vào đối tượng taiKhoan
                    taiKhoan.MatKhau = hashedPassword;
                    taiKhoan.MaTK = LayMaTK();
                    taiKhoan.Quyen = false;
                    taiKhoan.DiemTich = 0;
                    taiKhoan.Vip = false;

                    db.TaiKhoans.Add(taiKhoan);
                    db.SaveChanges();
                    CookieSevices.SetCookie(
                        HttpContext.ApplicationInstance.Context,
                        "MaTK", taiKhoan.MaTK.ToString()
                   );
                    return RedirectToAction("Index", "Sans");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Console.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }

            }

            return View(taiKhoan);
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        // GET: TaiKhoansUser
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
        }

        // GET: TaiKhoansUser/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoansUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TaiKhoansUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTK,TenTK,MatKhau,Email,HoTen,SDT,DiaChi,Vip,DiemTich,Quyen")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taiKhoan);
        }

        // GET: TaiKhoansUser/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoansUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTK,TenTK,MatKhau,Email,HoTen,SDT,DiaChi,Vip,DiemTich,Quyen")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details",new { id = taiKhoan.MaTK });
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoansUser/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoansUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public bool CheckRole(TaiKhoan taiKhoan)
        {
            var tk = db.TaiKhoans.FirstOrDefault(a => a.Email == taiKhoan.Email && a.MatKhau == taiKhoan.MatKhau);

            if (tk != null)
            {
                // Xác thực thành công
                if (tk.Quyen == true) // Kiểm tra "Quyen" có giá trị "admin" (hoặc true) hay không
                {
                    // Đặt vai trò "admin" cho người dùng
                    var identity = new ClaimsIdentity(new[] {
                        new Claim(ClaimTypes.Name, tk.TenTK),
                        new Claim(ClaimTypes.Role, "Admin")
                    }, "ApplicationCookie");

                    // Đăng nhập người dùng
                    var ctx = Request.GetOwinContext();
                    var authManager = ctx.Authentication;
                    authManager.SignIn(identity);
                    return true;
                }
                return false;
            }
            return false;
        }
    }
}

QuanLySanBanh/Views/TaiKhoansUser/Create.cshtml
@model QuanLySanBanh.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaiKhoan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaTK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaTK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaTK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenTK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Vip)
                    @Html.ValidationMessageFor(model => model.Vip, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiemTich, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiemTich, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiemTich, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quyen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Quyen)
                    @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLySanBanh/Views/TaiKhoansUser/Delete.cshtml
@model QuanLySanBanh.Models.TaiKhoan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiemTich)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiemTich)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quyen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quyen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLySanBanh/Views/TaiKhoansUser/Details.cshtml
@model QuanLySanBanh.Models.TaiKhoan

@*@{
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_Layout2.cshtml";
    }

    <h2>Details</h2>

    <div>
        <h4>TaiKhoan</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TenTK)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TenTK)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MatKhau)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HoTen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HoTen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Vip)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vip)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiemTich)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiemTich)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quyen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quyen)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MaTK }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    String Vip;
}

<style>
    .group-info {
        margin: 30px 0;
        display: flex;
        justify-content: space-between;
    }
</style>
<div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
    <div style=" background-color: #ee1e46; padding: 16px 88px; color: #fff; width: 500px;">
        <h2>Thông tin tài khoản</h2>
    </div>
    <div style="padding: 0 30px; border: 3px solid rgba(255, 255, 255, 0.1); width: 500px;">
        <div class="group-info">
            <h5>Tên tài khoản:</h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.TenTK</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Email: </h5>
            <div style="width: 211px">
                <h5 style="word-break:break-word">@Model.Email</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Họ và tên: </h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.HoTen</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Số Điện thoại:  </h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.SDT</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Địa chỉ: </h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.DiaChi</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Thành viên:</h5>
            <div style="width: 211px">
                @{
                    if (Model.Vip == true)
                    {
                        Vip = "Vip";
                    }
                    else
                    {
                        Vip = "Thường";
                    }
                }
                <h5 style="word-wrap:break-word">@Vip</h5>
            </div>
        </div>
        <div class="group-info">
            <h5>Điểm tích:</h5>
            <div style="width: 211px">
                <h5 style="word-wrap:break-word">@Model.DiemTich</h5>
            </div>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
            @Html.ActionLink("Đăng xuất", "Login", new { }, new { @class = "btn btn-outline-primary" })
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaTK }, new { @class = "btn btn-outline-danger" })
        </div>
    </div>
</div>

QuanLySanBanh/Views/TaiKhoansUser/Index.cshtml
@model IEnumerable<QuanLySanBanh.Models.TaiKhoan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenTK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatKhau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiemTich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quyen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenTK)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MatKhau)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiemTich)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quyen)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaTK }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaTK }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaTK })
        </td>
    </tr>
}

</table>

QuanLySanBanh/Views/TaiKhoansUser/Login.cshtml
@model QuanLySanBanh.Models.TaiKhoan
@{
    ViewBag.Title = "Login";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/Content/dangNhap.css">
    <title>Đăng nhập</title>
    <style>
        .inputbox ion-icon {
            right: 20px;
            top: 15px;
        }
    </style>
</head>
<body>
    <section>
        <div class="form-box">
            <div class="form-value">
                @using (Html.BeginForm("Login", "TaiKhoansUser", FormMethod.Post))
                {
                @Html.AntiForgeryToken()
                <h2 class="group">Đăng nhập</h2>
                <div class="inputbox">
                    <ion-icon name="person-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.Email, new { type = "email", required = "required" })
                    <label for="">Email</label>
                </div>
                <div class="inputbox">
                    <ion-icon name="lock-closed-outline"></ion-icon>
                    @Html.PasswordFor(m => m.MatKhau, new { required = "required" })
                    <label for="">Mật khẩu</label>
                </div>
                <div class="forget">
                    <label for=""><input type="checkbox">Nhớ mật khẩu  <a href="#">Quên mật khẩu</a></label>
                </div>
                <button type="submit">Đăng nhập</button>
                <div class="register">
                    <p>Chưa có tài khoản</p>
                    <a href="/TaiKhoansUser/Register">Đăng ký</a>
                </div>
                }
            </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

QuanLySanBanh/Views/TaiKhoansUser/Register.cshtml
@model QuanLySanBanh.Models.TaiKhoan
@{
    ViewBag.Title = "Register";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/Content/dangNhap.css">
    <title>Đăng ký</title>
    <style>
        .inputbox ion-icon {
            right: 20px;
            top: 15px;
        }
    </style>
</head>
<body>
    <section>
        <div class="form-box">
            <div class="form-value">
                @using (Html.BeginForm("Register", "TaiKhoansUser", FormMethod.Post)) 
                {
                @Html.AntiForgeryToken()

                <h2>Đăng ký</h2>
                <div class="inputbox">
                    <ion-icon name="person-circle-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.TenTK, new { required = "required" })
                    <label for="">Tên tài khoản</label>
                    @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                </div>
                <div class="inputbox">
                    <ion-icon name="lock-closed-outline"></ion-icon>
                    @Html.PasswordFor(m => m.MatKhau, new { required = "required" })
                    <label for="">Mật khẩu</label>
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
                <div class="inputbox">
                    <ion-icon name="mail-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.Email, new { type = "email", required = "required" })
                    <label for="">Email</label>
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
                <div class="inputbox">
                    <ion-icon name="person-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.HoTen, new { required = "required" })
                    <label for="">Họ và tên</label>
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
                <div class="inputbox">
                    <ion-icon name="call-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.SDT, new { type = "number", required = "required" })
                    <label for="">Số điện thoại</label>
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
                <div class="inputbox">
                    <ion-icon name="location-outline"></ion-icon>
                    @Html.TextBoxFor(m => m.DiaChi, new { required = "required" })
                    <label for="">Địa chỉ</label>
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
                <button type="submit">Đăng ký</button>
                <div class="register">
                    <p>Đã có tài khoản <a href="/TaiKhoans/Login">Đăng nhập</a></p>
                </div>
                }
            </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>